name: personal-website-development

services:
    nextjs:
        container_name: nextjs
        build:
            context: .
            target: dev
        restart: always
        command: "npm run dev"
        volumes:
            - nextjs-node-modules-folder:/app/node_modules
            - nextjs-next-folder:/app/.next
        ports:
            - 3000:3000

    nginx:
        container_name: nginx
        image: nginx:1.27
        restart: always
        depends_on:
            - nextjs
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./utils/nginx/nginx.dev.conf:/etc/nginx/nginx.conf

volumes:
    nextjs-node-modules-folder:
    nextjs-next-folder:
