name: personal-website-production

services:
    traefik:
        image: "traefik:v3.3"
        container_name: "traefik"
        restart: always
        command:
            - "traefik.enable=true"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./utils/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
            - "./utils/letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    nextjs:
        container_name: nextjs
        image: iwolf22/personal-website:latest
        restart: always
        environment:
            NODE_ENV: production
        labels:
            - "traefik.enable=true" # this container can use traefik
            - "traefik.http.routers.nextjs.rule=Host(`joshuadierickse.me`)" # subdomain
            - "traefik.http.routers.nextjs.entrypoints=websecure" # http or https
            - "traefik.http.routers.nextjs.tls=true" # http or https
            - "traefik.http.routers.nextjs.tls.certresolver=myresolver"

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        labels:
        - "traefik.enable=true" # Enable Traefik for this container
        - "traefik.http.routers.nginx.rule=Host(`grafana.joshuadierickse.me`)" # subdomain for Apache
        - "traefik.http.routers.nginx.entrypoints=websecure" # use https
        - "traefik.http.routers.nginx.tls=true"  # Enable TLS for Apache
        - "traefik.http.routers.nginx.tls.certresolver=myresolver" # Use the same cert resolver as Next.js

volumes:
    nextjs-node-modules-folder:
    nextjs-next-folder:
