name: personal-website-production

services:
    # =============================================
    # Personal Website
    # =============================================
    traefik:
        container_name: traefik
        image: traefik:v3.3
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./utils/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./utils/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    nextjs:
        container_name: nextjs
        image: iwolf22/personal-website:latest
        restart: always
        environment:
            NODE_ENV: production
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextjs.rule=Host(`joshuadierickse.me`)"
            - "traefik.http.routers.nextjs.entrypoints=websecure"
            - "traefik.http.routers.nextjs.tls=true"
            - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    # =============================================
    # Authentik
    # =============================================
    postgresql:
        container_name: authentik-postgresql
        image: docker.io/library/postgres:16-alpine
        restart: unless-stopped
        volumes:
            - authentik-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
            POSTGRES_USER: ${AUTHENTIK_POSTGRES_USER}
            POSTGRES_DB: ${AUTHENTIK_POSTGRES_DB}
        ports:
            - 5432:5432
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"


    redis:
        container_name: authentik-redis
        image: docker.io/library/redis:alpine
        command: --save 60 1 --loglevel warning
        restart: unless-stopped
        volumes:
            - authentik-redis:/data
        ports:
            - 6379:6379
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"


    server:
        container_name: authentik-server
        image: ghcr.io/goauthentik/server:2024.12.2
        restart: unless-stopped
        command: server
        environment:
            AUTHENTIK_REDIS__HOST: redis
            AUTHENTIK_POSTGRESQL__HOST: postgresql
            AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER}
            AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB}
            AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
        volumes:
            - ./utils/authentik/media:/media
            - ./utils/authentik/custom-templates:/templates
        env_file:
            - .env.authentik
        ports:
            - 9000:9000
            - 9443:9443
        depends_on:
            - postgresql
            - redis
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.authentik.rule=Host(`authentik.joshuadierickse.me`)"
            - "traefik.http.routers.authentik.entrypoints=websecure"
            - "traefik.http.routers.authentik.tls=true"
            - "traefik.http.routers.authentik.tls.certresolver=myresolver"
            - "traefik.http.routers.authentik.service=authentik-server"
            - "traefik.http.services.authentik-server.loadBalancer.server.port=9000"
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    worker:
        container_name: authentik-worker
        image: ghcr.io/goauthentik/server:2024.12.2
        restart: unless-stopped
        command: worker
        environment:
            AUTHENTIK_REDIS__HOST: redis
            AUTHENTIK_POSTGRESQL__HOST: postgresql
            AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER}
            AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB}
            AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
        # `user: root` and the docker socket volume are optional.
        # See more for the docker socket integration here:
        # https://goauthentik.io/docs/outposts/integrations/docker
        # Removing `user: root` also prevents the worker from fixing the permissions
        # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
        # (1000:1000 by default)
        user: root
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./media:/media
            - ./certs:/certs
            - ./custom-templates:/templates
        env_file:
            - .env.authentik
        depends_on:
            - postgresql
            - redis
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    # =============================================
    # Portainer
    # =============================================
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:2.26.1
        command: -H unix:///var/run/docker.sock
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.joshuadierickse.me`)"
            - "traefik.http.routers.portainer.entrypoints=websecure"
            - "traefik.http.routers.portainer.tls=true"
            - "traefik.http.routers.portainer.tls.certresolver=myresolver"
            - "traefik.http.routers.portainer.service=portainer"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    # =============================================
    # Observability
    # =============================================
    grafana:
        container_name: grafana
        image: grafana/grafana:11
        restart: unless-stopped
        volumes:
            - ./utils/grafana/provisioning:/etc/grafana/provisioning
            - grafana:/var/lib/grafana
        env_file:
            - .env.grafana
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grafana.rule=Host(`grafana.joshuadierickse.me`)"
            - "traefik.http.routers.grafana.entrypoints=websecure"
            - "traefik.http.routers.grafana.tls=true"
            - "traefik.http.routers.grafana.tls.certresolver=myresolver"
            - "traefik.http.routers.grafana.service=grafana"
            - "traefik.http.services.grafana.loadbalancer.server.port=3000"
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    prometheus:
        container_name: prometheus
        image: prom/prometheus
        restart: unless-stopped
        ports:
            - 9090:9090
        volumes:
            - ./utils/prometheus:/etc/prometheus
            - prometheus:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=90d"
            - "--storage.tsdb.retention.size=10GB"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/proemtheus/consoles"
            - "--web.enable-admin-api"
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor
        restart: unless-stopped
        ports:
            - 9250:9250
        privileged: true
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        devices:
            - /dev/kmsg
        command:
            - "-port=9250"
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter
        restart: unless-stopped
        ports:
            - 9100:9100
        pid: host
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.rootfs=/rootfs"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    smartctl:
        container_name: smartctl
        image: matusnovak/prometheus-smartctl
        ports:
            - 9902:9902
        restart: unless-stopped
        privileged: true
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    loki:
        container_name: loki
        image: grafana/loki:3.0.0
        ports:
            - 3100:3100
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./utils/loki/loki.yaml:/etc/loki/loki.yaml
        labels:
            - "logging=promtail"
            - "logging_jobname=containerlogs"

    promtail:
        container_name: promtail
        image: grafana/promtail:3.0.0
        volumes:
            - ./utils/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
            - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
        command: -config.file=/etc/promtail/docker-config.yaml
        depends_on:
            - loki
        labels:
            logging: "promtail"
            logging_jobname: "containerlogs"

volumes:
    nextjs-node-modules-folder:
    nextjs-next-folder:
    authentik-postgres:
    authentik-redis:
    portainer-data:
    grafana:
    prometheus:
