name: just-personal-website-production

services:
    # =============================================
    # Personal Website
    # =============================================
    traefik:
        container_name: traefik
        image: traefik:v3.3
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./utils/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./utils/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro

    nextjs:
        container_name: nextjs
        image: iwolf22/personal-website:latest
        restart: unless-stopped
        environment:
            NODE_ENV: production
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextjs.rule=Host(`joshua.dierickse.com`)"
            - "traefik.http.routers.nextjs.entrypoints=websecure"
            - "traefik.http.routers.nextjs.tls=true"
            - "traefik.http.routers.nextjs.tls.certresolver=myresolver"

    # =============================================
    # Minecraft
    # =============================================
    minecraft:
        image: itzg/minecraft-server
        container_name: minecraft
        restart: unless-stopped
        environment:
            EULA: "true"
            TYPE: PAPER
            MEMORY: 2G
            WHITELIST: ${MINECRAFT_WHITELIST}
            OPS: ${MINECRAFT_OPS}
            MOTD: "Test"
            ICON: "https://cdna.artstation.com/p/assets/images/images/010/412/374/large/victycoon-art-logo-m-p262.jpg?1524275330"
        ports:
            - 25565:25565
        volumes:
            - /home/joshua/minecraft:/data

volumes:
    nextjs-node-modules-folder:
    nextjs-next-folder:
