name: personal-website-production

services:
    nextjs:
        container_name: nextjs
        image: iwolf22/personal-website:latest
        restart: always
        volumes:
            - ./:/app
            - nextjs-node-modules-folder:/app/node_modules
            - nextjs-next-folder:/app/.next
        ports:
            - 3000:3000

    nginx:
        container_name: nginx
        image: nginx:1.27
        restart: always
        depends_on:
            - nextjs
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./utils/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/www/:/var/www/certbot/
            - ./certbot/conf:/etc/letsencrypt

    certbot:
        container_name: certbot
        image: certbot/certbot:v2.11.0
        volumes:
            - ./certbot/www/:/var/www/certbot/
            - ./certbot/conf/:/etc/letsencrypt/
        command: certonly --webroot -w /var/www/certbot --force-renewal --email joshua.dierickse@gmail.com -d joshuadierickse.me --agree-tos

volumes:
    nextjs-node-modules-folder:
    nextjs-next-folder:
