import type { Metadata } from "next";

import ThemeContext from "@/components/custom/ThemeContext";
import localFont from "next/font/local";

import "./globals.css";

export const helvetica = localFont({
    src: "./../../public/fonts/HelveticaforTarget-Bold.ttf",
});

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ThemeContext>{children}</ThemeContext>
        </html>
    );
}
