import type { Metadata } from "next";

import ThemeContext from "@/components/custom/ThemeContext";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const helvetica = localFont({
    src: "./../../public/fonts/HelveticaforTarget-Bold.ttf",
});

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeContext>{children}</ThemeContext>
            </body>
        </html>
    );
}
