import type { Metadata } from "next";

import ThemeContext from "@/components/custom/ThemeContext";
import Footer from "@/components/general/Footer";
import Navbar from "@/components/general/Navbar";

import "./globals.css";

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ThemeContext>
                <div className="flex min-h-[calc(100vh)] flex-col justify-between">
                    <div>
                        <Navbar />
                        {children}
                    </div>
                    <Footer />
                </div>
            </ThemeContext>
        </html>
    );
}
