---
name: NextJS Docker Image Build # The name of a github workflow

on: # List of GitHub events that that will trigger a workflow
  push: # Run the GitHub workflow on a push to the main branch
    branches:
      - main

jobs: # A workflow can have multiple jobs run in parallel by default
  build-image: # job id is the key `build-image`
    name: Build Image # Name of the job
    runs-on: ubuntu-latest # Where the jon will be ran

    steps: # Each job run a sequence of steps
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub # Name of the first step
        uses: docker/login-action@v3 # Selects the GitHub Action to use
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Docker build # Name of a second step
        uses: docker/build-push-action@v6 # Second GitHub Action to use
        with:
          file: ./Web-Server/Dockerfile # Points to the Dockerfile
          context: ./Web-Server
          tags: iwolf22/personal-website:latest # Tag the docker image
          target: runner # Dockerfile stage
